[package]
name = "ffmpeg_ffi_test"
version = "0.1.0"
authors = ["Jan EkstrÃ¶m <jeebjp@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.20"

[build-dependencies]
bindgen = "0.25.5"
pkg-config = "0.3.9"
